exports.up = function(knex, Promise) {
    return knex.schema.createTable('people', table => {
    table.increments()
    table.string('first_name').notNullable().defaultsTo('none')
    table.string('last_name').defaultsTo(null)
    table.string('location').defaultsTo(null)
    table.string('birthday').defaultsTo(null)
    table.string('face_model').defaultsTo(null)
    table.string('facebook').defaultsTo(null)
    table.string('facebook_image').defaultsTo(null)
    table.string('flickr').defaultsTo(null)
    table.string('flickr_image').defaultsTo(null)
    table.string('foursquare').defaultsTo(null)
    table.string('foursquare_image').defaultsTo(null)
    table.string('gofundme').defaultsTo(null)
    table.string('gofundme_image').defaultsTo(null)
    table.string('goodreads').defaultsTo(null)
    table.string('goodreads_image').defaultsTo(null)
    table.string('googleplus').defaultsTo(null)
    table.string('googleplus_image').defaultsTo(null)
    table.string('instagram').defaultsTo(null)
    table.string('instagram_image').defaultsTo(null)
    table.string('linkedin').defaultsTo(null)
    table.string('linkedin_image').defaultsTo(null)
    table.string('livejournal').defaultsTo(null)
    table.string('livejournal_image').defaultsTo(null)
    table.string('meetup').defaultsTo(null)
    table.string('meetup_image').defaultsTo(null)
    table.string('myspace').defaultsTo(null)
    table.string('myspace_image').defaultsTo(null)
    table.string('pinterest').defaultsTo(null)
    table.string('pinterest_image').defaultsTo(null)
    table.string('tumblr').defaultsTo(null)
    table.string('tumblr_image').defaultsTo(null)
    table.string('twitter').defaultsTo(null)
    table.string('twitter_image').defaultsTo(null)
    table.string('yelp').defaultsTo(null)
    table.string('yelp_image').defaultsTo(null)
  })
}

exports.down = function(knex, Promise) {
    return knex.schema.dropTable('people')
}
